[package]
name = "hacspec"
version = "0.1.0"
authors = ["Denis Merigoux <denis.merigoux@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~2.33.1", features = ["yaml"]}
pretty = "0.10.0"
im = "15.0.0"
itertools = "0.9.0"
walkdir = "2.3.1"
serde_json = "1.0"
hacspec-sig = { path = "../utils/sig" }
heck = "0.3.1"
regex = "1.3.9"

[dev-dependencies]
assert_cmd = "1.0.1"
hacspec-lib = { path = "../lib" }
hacspec-chacha20 = { path = "../examples/hacspec-chacha20" }
hacspec-poly1305 = { path = "../examples/hacspec-poly1305" }
hacspec-chacha20poly1305 = { path = "../examples/hacspec-chacha20poly1305" }
