[workspace]
members = [
    "lib",
    "provider",
    "utils/dev",
    "utils/derive",
    "utils/evercrypt-provider",
    "utils/secret-integers",
    "utils/abstract-integers",
    "utils/attributes",
    "utils/rc-bench",
    "utils/rc-tests",
    "utils/util",
    "language",
    "examples/hacspec-curve25519",
    "examples/hacspec-chacha20",
    "examples/hacspec-poly1305",
    "examples/hacspec-chacha20poly1305",
    "examples/hacspec-gimli",
    "examples/hacspec-sha256",
    "examples/hacspec-sha3",
    "examples/hacspec-ntru-prime",
    "examples-unsafe",
    "examples/hacspec-riot-bootloader",
]
default-members = [
    "lib",
    "provider",
    "utils/dev",
    "utils/derive",
    "utils/secret-integers",
    "utils/abstract-integers",
    "utils/attributes",
    "utils/util",
    "examples/hacspec-curve25519",
    "examples/hacspec-chacha20",
    "examples/hacspec-poly1305",
    "examples/hacspec-chacha20poly1305",
    "examples/hacspec-gimli",
    "examples/hacspec-sha256",
    "examples/hacspec-sha3",
    "examples/hacspec-ntru-prime",
    "examples-unsafe",
    "examples/hacspec-riot-bootloader",
]

[profile.release]
debug = true
