[workspace]
members = [
    "lib",
    "utils/dev",
    "utils/derive",
    "utils/secret-integers",
    "utils/abstract-integers",
    "utils/attributes",
    "utils/provider",
    "utils/sig",
    "language",
    "examples/hacspec-chacha20",
    "examples/hacspec-poly1305",
    "examples/hacspec-chacha20poly1305",
    "examples/hacspec-sha256",
    "examples/hacspec-sha3",
    "examples/hacspec-ntru-prime",
    "examples-unsafe",
]
default-members = [
    "lib",
    "utils/dev",
    "utils/derive",
    "utils/secret-integers",
    "utils/abstract-integers",
    "utils/attributes",
    "utils/sig",
    "examples/hacspec-chacha20",
    "examples/hacspec-poly1305",
    "examples/hacspec-chacha20poly1305",
    "examples/hacspec-sha256",
    "examples/hacspec-sha3",
    "examples/hacspec-ntru-prime",
    "examples-unsafe",
]

[profile.release]
debug = true
