[package]
name = "rc-tests"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
evercrypt-provider = { path = "../evercrypt-provider" }
hacspec-provider = { path = "../../provider" }
chacha20poly1305 = "0.9"
serde_json = "1.0"
serde = {version = "=1.0.156", features = ["derive"]}
