[package]
name = "rc-bench"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
evercrypt-provider = { path = "../evercrypt-provider" }
hacspec-provider = { path = "../../provider" }
chacha20poly1305 = "0.9"
criterion = "^0.4"
rand = "^0.8"

[[bench]]
name = "benchmarks"
harness = false
