[package]
name = "evercrypt-provider"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

[features]
random = []

[dependencies]
evercrypt = "0.0.11"
hacspec-provider = { path = "../../provider" }
aead = { version = "0.4", features = ["alloc"] }

[dev-dependencies]
serde_json = "1.0"
serde = {version = "=1.0.156", features = ["derive"]}
rand = "0.8"
