[package]
name = "hacspec-util"
version = "0.1.0-beta.1"
authors = ["Denis Merigoux <denis.merigoux@gmail.com>"]
edition = "2018"
description = "hacspec utilities"
readme = "Readme.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hacspec/hacspec"

[dependencies]
serde = {version = "=1.0.156", features = ["derive"]}
syn = { version = "1.0.17", features= ["full", "visit"] }
