[package]
name = "abstract_integers"
version = "0.1.5"
authors = ["Denis Merigoux <denis.merigoux@gmail.com>"]
description = "Defining specification-friendly bounded natural integer types"
repository = "https://github.com/hacspec/hacspec"
edition = "2018"
keywords = ["integers", "specification"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
num = { version = "0.4", default-features = false }
num-bigint = { version = "0.4", default-features = false }

[dependencies.creusot-contracts]
git = "https://github.com/xldenis/creusot/"
branch = "master"
package = "creusot-contracts"

[features]
default = ["std"]
std = ["num/std", "num-bigint/std"]
contracts = []
